/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as MarketRouteImport } from './routes/market'
import { Route as ProductRouteImport } from './routes/product'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as DemoIndexRouteImport } from './routes/demo.index'
import { Route as DemoGraphRouteImport } from './routes/demo.graph'
import { Route as DemoSimulatorRouteImport } from './routes/demo.simulator'
import { Route as WorkspaceIndexRouteImport } from './routes/workspace.index'
import { Route as WorkspaceCorpusRouteImport } from './routes/workspace.corpus'
import { Route as WorkspaceRunsIndexRouteImport } from './routes/workspace.runs.index'
import { Route as WorkspaceRunsRunIdRouteImport } from './routes/workspace.runs.$runId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRoute = ProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DemoRoute,
} as any)
const DemoGraphRoute = DemoGraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => DemoRoute,
} as any)
const DemoSimulatorRoute = DemoSimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => DemoRoute,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceCorpusRoute = WorkspaceCorpusRouteImport.update({
  id: '/corpus',
  path: '/corpus',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceRunsIndexRoute = WorkspaceRunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceRunsRunIdRoute = WorkspaceRunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => WorkspaceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteWithChildren
  '/market': typeof MarketRoute
  '/product': typeof ProductRoute
  '/roadmap': typeof RoadmapRoute
  '/workspace': typeof WorkspaceRouteWithChildren
  '/demo/graph': typeof DemoGraphRoute
  '/demo/simulator': typeof DemoSimulatorRoute
  '/workspace/corpus': typeof WorkspaceCorpusRoute
  '/demo/': typeof DemoIndexRoute
  '/workspace/': typeof WorkspaceIndexRoute
  '/workspace/runs/$runId': typeof WorkspaceRunsRunIdRoute
  '/workspace/runs/': typeof WorkspaceRunsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/market': typeof MarketRoute
  '/product': typeof ProductRoute
  '/roadmap': typeof RoadmapRoute
  '/demo/graph': typeof DemoGraphRoute
  '/demo/simulator': typeof DemoSimulatorRoute
  '/workspace/corpus': typeof WorkspaceCorpusRoute
  '/demo': typeof DemoIndexRoute
  '/workspace': typeof WorkspaceIndexRoute
  '/workspace/runs/$runId': typeof WorkspaceRunsRunIdRoute
  '/workspace/runs': typeof WorkspaceRunsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteWithChildren
  '/market': typeof MarketRoute
  '/product': typeof ProductRoute
  '/roadmap': typeof RoadmapRoute
  '/workspace': typeof WorkspaceRouteWithChildren
  '/demo/graph': typeof DemoGraphRoute
  '/demo/simulator': typeof DemoSimulatorRoute
  '/workspace/corpus': typeof WorkspaceCorpusRoute
  '/demo/': typeof DemoIndexRoute
  '/workspace/': typeof WorkspaceIndexRoute
  '/workspace/runs/$runId': typeof WorkspaceRunsRunIdRoute
  '/workspace/runs/': typeof WorkspaceRunsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/market'
    | '/product'
    | '/roadmap'
    | '/workspace'
    | '/demo/graph'
    | '/demo/simulator'
    | '/workspace/corpus'
    | '/demo/'
    | '/workspace/'
    | '/workspace/runs/$runId'
    | '/workspace/runs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/market'
    | '/product'
    | '/roadmap'
    | '/demo/graph'
    | '/demo/simulator'
    | '/workspace/corpus'
    | '/demo'
    | '/workspace'
    | '/workspace/runs/$runId'
    | '/workspace/runs'
  id:
    | '__root__'
    | '/'
    | '/demo'
    | '/market'
    | '/product'
    | '/roadmap'
    | '/workspace'
    | '/demo/graph'
    | '/demo/simulator'
    | '/workspace/corpus'
    | '/demo/'
    | '/workspace/'
    | '/workspace/runs/$runId'
    | '/workspace/runs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRoute: typeof DemoRouteWithChildren
  MarketRoute: typeof MarketRoute
  ProductRoute: typeof ProductRoute
  RoadmapRoute: typeof RoadmapRoute
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/': {
      id: '/demo/'
      path: '/'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/graph': {
      id: '/demo/graph'
      path: '/graph'
      fullPath: '/demo/graph'
      preLoaderRoute: typeof DemoGraphRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/simulator': {
      id: '/demo/simulator'
      path: '/simulator'
      fullPath: '/demo/simulator'
      preLoaderRoute: typeof DemoSimulatorRouteImport
      parentRoute: typeof DemoRoute
    }
    '/workspace/': {
      id: '/workspace/'
      path: '/'
      fullPath: '/workspace/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/corpus': {
      id: '/workspace/corpus'
      path: '/corpus'
      fullPath: '/workspace/corpus'
      preLoaderRoute: typeof WorkspaceCorpusRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/runs/': {
      id: '/workspace/runs/'
      path: '/runs'
      fullPath: '/workspace/runs/'
      preLoaderRoute: typeof WorkspaceRunsIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/runs/$runId': {
      id: '/workspace/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/workspace/runs/$runId'
      preLoaderRoute: typeof WorkspaceRunsRunIdRouteImport
      parentRoute: typeof WorkspaceRoute
    }
  }
}

interface DemoRouteChildren {
  DemoGraphRoute: typeof DemoGraphRoute
  DemoSimulatorRoute: typeof DemoSimulatorRoute
  DemoIndexRoute: typeof DemoIndexRoute
}

const DemoRouteChildren: DemoRouteChildren = {
  DemoGraphRoute: DemoGraphRoute,
  DemoSimulatorRoute: DemoSimulatorRoute,
  DemoIndexRoute: DemoIndexRoute,
}

const DemoRouteWithChildren = DemoRoute._addFileChildren(DemoRouteChildren)

interface WorkspaceRouteChildren {
  WorkspaceCorpusRoute: typeof WorkspaceCorpusRoute
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
  WorkspaceRunsRunIdRoute: typeof WorkspaceRunsRunIdRoute
  WorkspaceRunsIndexRoute: typeof WorkspaceRunsIndexRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceCorpusRoute: WorkspaceCorpusRoute,
  WorkspaceIndexRoute: WorkspaceIndexRoute,
  WorkspaceRunsRunIdRoute: WorkspaceRunsRunIdRoute,
  WorkspaceRunsIndexRoute: WorkspaceRunsIndexRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRoute: DemoRouteWithChildren,
  MarketRoute: MarketRoute,
  ProductRoute: ProductRoute,
  RoadmapRoute: RoadmapRoute,
  WorkspaceRoute: WorkspaceRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
